// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	schedule "github.com/Netflix/chaosmonkey/v2/schedule"

	time "time"
)

// SchedStore is an autogenerated mock type for the SchedStore type
type SchedStore struct {
	mock.Mock
}

// Publish provides a mock function with given fields: date, sched
func (_m *SchedStore) Publish(date time.Time, sched *schedule.Schedule) error {
	ret := _m.Called(date, sched)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time, *schedule.Schedule) error); ok {
		r0 = rf(date, sched)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Retrieve provides a mock function with given fields: date
func (_m *SchedStore) Retrieve(date time.Time) (*schedule.Schedule, error) {
	ret := _m.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 *schedule.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time) (*schedule.Schedule, error)); ok {
		return rf(date)
	}
	if rf, ok := ret.Get(0).(func(time.Time) *schedule.Schedule); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedule.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSchedStore creates a new instance of SchedStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedStore {
	mock := &SchedStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
