// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	io "io"

	config "github.com/Netflix/chaosmonkey/v2/config"

	mock "github.com/stretchr/testify/mock"
)

// RemoteConfigFactory is an autogenerated mock type for the RemoteConfigFactory type
type RemoteConfigFactory struct {
	mock.Mock
}

// Get provides a mock function with given fields: rp
func (_m *RemoteConfigFactory) Get(rp config.RemoteProvider) (io.Reader, error) {
	ret := _m.Called(rp)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(config.RemoteProvider) (io.Reader, error)); ok {
		return rf(rp)
	}
	if rf, ok := ret.Get(0).(func(config.RemoteProvider) io.Reader); ok {
		r0 = rf(rp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(config.RemoteProvider) error); ok {
		r1 = rf(rp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: rp
func (_m *RemoteConfigFactory) Watch(rp config.RemoteProvider) (io.Reader, error) {
	ret := _m.Called(rp)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(config.RemoteProvider) (io.Reader, error)); ok {
		return rf(rp)
	}
	if rf, ok := ret.Get(0).(func(config.RemoteProvider) io.Reader); ok {
		r0 = rf(rp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(config.RemoteProvider) error); ok {
		r1 = rf(rp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRemoteConfigFactory creates a new instance of RemoteConfigFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteConfigFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteConfigFactory {
	mock := &RemoteConfigFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
