// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InstanceGroup is an autogenerated mock type for the InstanceGroup type
type InstanceGroup struct {
	mock.Mock
}

// Account provides a mock function with no fields
func (_m *InstanceGroup) Account() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Account")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// App provides a mock function with no fields
func (_m *InstanceGroup) App() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for App")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Cluster provides a mock function with no fields
func (_m *InstanceGroup) Cluster() (string, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cluster")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func() (string, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Region provides a mock function with no fields
func (_m *InstanceGroup) Region() (string, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Region")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func() (string, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Stack provides a mock function with no fields
func (_m *InstanceGroup) Stack() (string, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stack")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func() (string, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// String provides a mock function with no fields
func (_m *InstanceGroup) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewInstanceGroup creates a new instance of InstanceGroup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInstanceGroup(t interface {
	mock.TestingT
	Cleanup(func())
}) *InstanceGroup {
	mock := &InstanceGroup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
