// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	schedule "github.com/Netflix/chaosmonkey/v2/schedule"
	mock "github.com/stretchr/testify/mock"
)

// Constrainer is an autogenerated mock type for the Constrainer type
type Constrainer struct {
	mock.Mock
}

// Filter provides a mock function with given fields: _a0
func (_m *Constrainer) Filter(_a0 schedule.Schedule) schedule.Schedule {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 schedule.Schedule
	if rf, ok := ret.Get(0).(func(schedule.Schedule) schedule.Schedule); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(schedule.Schedule)
	}

	return r0
}

// NewConstrainer creates a new instance of Constrainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConstrainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Constrainer {
	mock := &Constrainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
