// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// float64Rand is an autogenerated mock type for the float64Rand type
type float64Rand struct {
	mock.Mock
}

// Float64 provides a mock function with no fields
func (_m *float64Rand) Float64() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Float64")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// newFloat64Rand creates a new instance of float64Rand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFloat64Rand(t interface {
	mock.TestingT
	Cleanup(func())
}) *float64Rand {
	mock := &float64Rand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
